version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    environment:
      NODE_ENV: ${DEV_NODE_ENV}
      DATABASE_URL: ${DEV_DATABASE_URL}
    volumes:
      - ..:/usr/src/app
