version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      DEV_DATABASE_URL: ${DEV_DATABASE_URL}
    volumes:
      - ..:/usr/src/app
