# Use an appropriate base image with Node.js installed
FROM node:20

# Set Working Directory
RUN mkdir -p /app
WORKDIR /app

# Install Node Modules
COPY package.json package-lock.json ./
RUN npm install

# Copy Source Code
COPY . ./

# Expose the port your app runs on
EXPOSE 3000

# Command to run your application
CMD ["npm", "start"]
