# Use the official Node.js 20.13.1 image as the base image
FROM node:20.13.1

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install || { cat /usr/src/app/npm-debug.log; exit 1; }

# Verify that node_modules is created
RUN if [ -d "node_modules" ]; then echo "node_modules directory exists"; else echo "node_modules directory does not exist"; fi

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the app
CMD ["npm", "start"]
