name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull Docker image
        run: sudo docker pull waqarhussain4154/hannen-node:latest

      - name: Stop and Remove Old Docker Container
        run: |
          sudo docker stop hannen-node || true
          sudo docker rm -f hannen-node || true

      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name hannen-node waqarhussain4154/hannen-node

      - name: Verify Container is Running
        run: |
          docker ps -a
          curl http://localhost:8080
