name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files for debugging
        run: ls -al

      - name: List files in docker folder for debugging
        run: ls -al docker

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy docker-compose file to server
        run: |
          scp -o StrictHostKeyChecking=no ./docker/docker-compose.prod.yml ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }}:/home/${{ secrets.AWS_USER }}/docker-compose.yml

      - name: Create .env file on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            echo "NODE_ENV=${{ secrets.NODE_ENV }}" > /home/${{ secrets.AWS_USER }}/.env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> /home/${{ secrets.AWS_USER }}/.env
            # Add other environment variables as needed
          EOF

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            cd /home/${{ secrets.AWS_USER }}
            docker-compose down
            docker-compose pull
            docker-compose up -d
          EOF
