name: Run Dev haneen-node
on:
  push:
    branches: ["dev"]
jobs:
  deploy:
    runs-on: [self-hosted, dev]
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          touch .env
          echo PORT='${{ secrets.PORT_DEV }}' >> .env
          echo MONGO_URI='${{ secrets.MONGO_URI_DEV }}' >> .env
          echo JWT_SECRET='${{ secrets.JWT_SECRET_DEV }}' >> .env
          echo NODE_ENV='${{ secrets.NODE_ENV_DEV }}' >> .env
          cat .env
      - name: Close previous docker containers
        run: sudo docker compose -f docker-compose-dev.yml -p dev-haneen-node down
      - name: Run docker with build
        run: sudo docker compose -f docker-compose-dev.yml -p dev-haneen-node up --build -d
