name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    # Remove or comment out the Run tests step
    # - name: Run tests
    #   run: npm test

    - name: Build Docker image
      run: docker build -t haneen-node:latest .

    - name: Run Docker container
      run: docker run -d -p 8080:8080 haneen-node:latest
