name: Deploy to EC2 (Development)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r . ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app

      - name: SSH into EC2 and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          mkdir -p /home/ubuntu/app
          cd /home/ubuntu/app
          export NODE_ENV=${{ secrets.DEV_NODE_ENV }}
          export DATABASE_URL=${{ secrets.DEV_DATABASE_URL }}
          docker-compose -f docker/docker-compose.dev.yml up --build -d
          EOF
